<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'BricksFile\Module'     => __DIR__ . '/Module.php',
  'Bricks\File\Directory' => __DIR__ . '/src/Bricks/File/Directory.php',
  'Bricks\File\File'      => __DIR__ . '/src/Bricks/File/File.php',
);
