<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Bricks\File\Directory'          => __DIR__ . '/src/Bricks/File/Directory.php',
    'Bricks\File\DirectoryInterface' => __DIR__ . '/src/Bricks/File/DirectoryInterface.php',
    'Bricks\File\File'               => __DIR__ . '/src/Bricks/File/File.php',
    'Bricks\File\FileInterface'      => __DIR__ . '/src/Bricks/File/FileInterface.php',
);
